# Configuration for the ClickHouse cluster to be started
module:
  persistence: true
  #共享存储，打通fedx-api worker的/data目录
  share: false
nfs:
  nfsPath: /mjmp/nfs
  nfsServer: 172.20.8.55

clickhouse:
  # default cluster name
  clusterName: cluster

  ## the limit and require of resources
  resources:
    requestsMemery: "5Gi"
    requestsCpu: "1"
    limitsMemery: "50Gi"
    limitsCpu: "8"

  # User Configuration
  users:
  - username: default
    password: ck@12345
  # Port configuration, see https://clickhouse.tech/docs/en/interfaces/
  ports:
    # Port for the native CLI interface, see https://clickhouse.tech/docs/en/interfaces/tcp/
    native: 9000

    # Port for HTTP/REST interface, see https://clickhouse.tech/docs/en/interfaces/http/
    http: 8123

  # If no explicit configuration for PersistentVolumeClaims is defined with the replicas,
  # create new PersistentVolumeClaims with this storage class:
  storageClassName: nfs

  # Shart configuration, see https://clickhouse.tech/docs/en/operations/table_engines/distributed/
  shards:
  - name: shard0
    replicas:
    - name: shard0-replica0
    # - name: shard0-replica1

  # ClickHouse server image configuration
  #image: radondb/clickhouse-server:21.1.3.32
  image: registry.zet-fl.com/fedx/clickhouse-server:22.3.6.5
  imagePullPolicy: IfNotPresent

  # By default, this helm chart will create a service for getting access to the cluster.
  # Using this configuration it is possible to adjust the service settings.
  service:
    # Default create service by the helm chart.
    enabled: true

    # Type of the service. Use ClusterIP for internal access, LoadBalancer for external access.
    type: ClusterIP

    # Define the loadBalancerIP if type is set to LoadBalancer and you want to request a special IP address.
    loadBalancerIP:

  ipv4: true
  ipv6: false

  livenessProbe:
    initialDelaySeconds: "30"
    periodSeconds: "30"
    timeoutSeconds: "5"
    failureThreshold: "3"
    successThreshold: "1"

# zookeeper configuration
zookeeper:
  replicas: 1

  # configuration for zookeeper instance
  image: registry.zet-fl.com/fedx/zookeeper:3.6.1
  imagePullPolicy: IfNotPresent

  resources:
    memory: "1Gi"
    cpu: "0.5"

storage:
  ckSize: 50Gi
  zkSize: 10Gi
