apiVersion: v1
kind: Service
metadata:
  name: fedx-helper
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fedx-helper
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedx-helper
  namespace: {{ .Release.Namespace }}
  labels:
    app: fedx-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedx-helper
  template:
    metadata:
      labels:
        app: fedx-helper
    spec:
      containers:
      - name: fedx-helper
        image: {{ .Values.image.repository }}/fedx-doc:{{ .Values.image.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{ if .Values.module.resourceConf }}
        resources:
        {{- with index .Values "fedx-helper" "resources" }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.module.readinessProbe }}
        readinessProbe:
          tcpSocket:
            port: 8080
          {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
        volumeMounts:
          - name: fedx-helper
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: fedx-helper
          configMap:
            name: fedx-helper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fedx-helper
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  102400;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      underscores_in_headers on;
      client_max_body_size 10240m;
      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }

      server {
        listen 8080;
        server_name _;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html;
        }
      }
    }
