apiVersion: v1
kind: Service
metadata:
  name: fedx-job-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fedx-job-worker
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedx-job-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: fedx-job-worker
spec:
  selector:
    matchLabels:
      app: fedx-job-worker
  replicas: 1
  template:
    metadata:
      name: fedx-job-worker
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: fedx-job-worker
    spec:
      {{- if .Values.module.initContainers }}
      initContainers:
        {{- include "initContainers" . | indent 6 }}
      {{- end }}
      containers:
      - name: fedx-job-worker
        image: {{ .Values.image.repository }}/fedx-job-worker:{{ .Values.image.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{ if .Values.module.resourceConf }}
        resources:
        {{- with index .Values "fedx-job-worker" "resources" }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.module.readinessProbe }}
        readinessProbe:
          tcpSocket:
            port: 8081
          {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
      {{- if .Values.module.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: 8081
          {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
        volumeMounts:
          - name: fedx-job-worker
            mountPath: /fedx-job-worker/application.yml
            subPath: application.yml
          {{ if .Values.module.persistence  }}
          - name: datax-job
            mountPath: /datax/job
          {{ end }}
          - name: data
            mountPath: /data
          - name: cm-krb5
            mountPath: /etc/krb5.conf
            subPath: krb5.conf
          - name: cm-krb5
            mountPath: /etc/keytab/user.keytab
            subPath: user.keytab
      volumes:
      - name: fedx-job-api
        configMap:
          name: fedx-job-api
      - name: fedx-job-worker
        configMap:
          name: fedx-job-worker
      - name: cm-krb5
        configMap:
          name: cm-krb5
      {{ if .Values.module.persistence }}
      - name: datax-job
        persistentVolumeClaim:
          claimName: pvc-datax
      {{ end }}
      - name: data
        persistentVolumeClaim:
          claimName: pvc-share
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fedx-job-worker
  labels:
    app: fedx-job-worker
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |-
    server:
      port: 8081
      author: {{ .Values.ip.localIp }}
      
    #spring 基础配置
    spring:
      application:
        name: fedx-etl-job-worker
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.name }}?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: {{ .Values.mysql.user }}
          password: {{ .Values.mysql.passwd }}
        clickhouse:
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          url: {{ .Values.clickhouse.url }}
          username: {{ .Values.clickhouse.username }}
          password: {{ .Values.clickhouse.passwd }}
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT

    #大数据工作流基础配置
    fedx-job-worker:
      exception:
        trace-enabled: true
      node-id: 1
      worker:
        datax:
          worker-thread: 5
        task-each-round: 2
      schedule-per-millsec: 60000
      release-per-millsec: 600000
      dataset-expire-cron: "0 0 1 * * ?"
      model-component-data-download: 60000

    # RestTemplate配置
    rest:
      connection:
        connection-request-timeout: 15000
        connect-timeout: 15000
        read-timeout: 15000

    # Swagger API-Doc配置
    api-doc:
      title: ${spring.application.name} Zetyun联邦学习平台ETL Worker服务
      description: Zetyun联邦学习ETL作业Workder服务(运行作业)
      termsOfServiceUrl: http://www.zetyun.com
      contact:
        name: Contact
        url: http://www.zetyun.com
        email: contact@zetyun.com
      version: 1.0.0-SNAPSHOT

    #本端fate flow配置，即原生fate python pod 的 9380端口 = pythonSvcName:9380
    fate-flow:
      address: http://fateflow.{{ .Values.fate.namespace }}:9380
    namenode:
      address: hdfs://fedx-proxy-cluster-ip.{{ .Release.Namespace }}:9000
    fedx-api:
      address: http://fedx-api:8081
    realai:
      uri: {{ index .Values "fedx-job-worker" "realai" "url" }}

    # DATAX 配置 hdfs hive 的 reader writer 配置信息
    datax:
      hook:
        enabled: true
        url: http://fedx-job-api.{{ .Release.Namespace }}:8081/update

    file:
      path: "/data/"
