apiVersion: v1
kind: Service
metadata:
  name: fedx-job-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fedx-job-api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedx-job-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: fedx-job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedx-job-api
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: fedx-job-api
    spec:
      {{- if .Values.module.initContainers }}
      initContainers:
        {{- include "initContainers" . | indent 6 }}
      {{- end }}
      containers:
      - name: fedx-job-api
        image: {{ .Values.image.repository }}/fedx-job-api:{{ .Values.image.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{ if .Values.module.resourceConf }}
        resources:
        {{- with index .Values "fedx-job-api" "resources" }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.module.readinessProbe }}
        readinessProbe:
          tcpSocket:
            port: 8081
          {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
      {{- if .Values.module.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: 8081
          {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
        volumeMounts:
          - name: fedx-job-api
            mountPath: /fedx-job-api/application.yml
            subPath: application.yml
      volumes:
        - name: fedx-job-api
          configMap:
            name: fedx-job-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fedx-job-api
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    server:
      port: 8081
      author: {{ .Values.ip.localIp }}
    spring:
      application:
        name: fedx-job-api
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.port }}/{{ .Values.mysql.name }}?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: {{ .Values.mysql.user }}
          password: {{ .Values.mysql.passwd }}
        clickhouse:
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          url: {{ .Values.clickhouse.url }}{{ .Values.clickhouse.database }}
          username: {{ .Values.clickhouse.username }}
          password: {{ .Values.clickhouse.passwd }}
        clickhouse2:
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          url: {{ .Values.clickhouse2.url }}
          username: {{ .Values.clickhouse.username }}
          password: {{ .Values.clickhouse.passwd }}

    fedx-job-api:
      exception:
        trace-enabled: true
      node-id: 1
      party-id: 1000
    # RestTemplate配置
    rest:
      connection:
        connection-request-timeout: 15000
        connect-timeout: 15000
        read-timeout: 15000

    fedx:
      fate:
        address: http://fate-proxy-cluster-ip.{{ .Values.fate.namespace }}
        port: 9380
      api:
        address: http://fedx-api:8081
      namenode:
        address: hdfs://fedx-proxy-cluster-ip.{{ .Release.Namespace }}:9000
