name: fate-1000
namespace: fate-1000
chartName: fate
chartVersion: v1.7.2-fedx-persistence
partyId: 1000
registry: "registry.zet-fl.com/fedx"
imageTag: "1.7.2-release"
pullPolicy: 
imagePullSecrets: 
- name: myregistrykey
persistence: true
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
ingressClassName: nginx
modules:
  - mysql
  - python
  - fateboard
  - client
  - spark
  - hdfs
  - nginx
  - pulsar

backend: spark_pulsar

python:
  type: ClusterIP
  logLevel: DEBUG
  storageClass: "nfs"
  accessMode: ReadWriteMany
  size: 30Gi

nginx:
  type: ClusterIP
  route_table: 
    1000: 
      fateflow: 
        - host: fate-proxy-cluster-ip
          http_port: 1007
    1100: 
      fateflow: 
        - host: fate-proxy-cluster-ip
          http_port: 1107
    2000: 
      fateflow: 
        - host: fate-proxy-cluster-ip
          http_port: 2007

spark: 
  worker:
    replicas: 3
    resources:
      requests:
        cpu: "2"
        memory: "2Gi"
      limits:
        cpu: "32"
        memory: "33Gi"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                fateMoudle: spark-worker
            topologyKey: kubernetes.io/hostname

pulsar:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            fateMoudle: pulsar
        topologyKey: kubernetes.io/hostname
        namespaces:
        - "fate-1000"
        - "fate-1100" 
        - "fate-2000"
  type: ClusterIP
  storageClass: "nfs"
  accessMode: ReadWriteMany
  size: 30Gi
  route_table:
    1000:
      host: fate-proxy-cluster-ip
      port: 1009
    1100:
      host: fate-proxy-cluster-ip
      port: 1109
    2000:
      host: fate-proxy-cluster-ip
      port: 2009

servingIp: fate-proxy-cluster-ip
servingPort: 8000

client:
  storageClass: "nfs"
  accessMode: ReadWriteMany
  size: 10Gi

mysql:
  # ip: 172.20.8.110
  # user: root
  # password: Wa@123456
  # port: 30306
  database: eggroll_meta
  storageClass: "nfs"
  accessMode: ReadWriteMany
  size: 10Gi

hdfs:
  namenode:
    storageClass: "nfs"
    accessMode: ReadWriteMany
    size: 10Gi
  datanode:
    storageClass: "nfs"
    accessMode: ReadWriteOnce
    size: 20Gi
